### PR TITLE
Retire redundant policy

### PR DESCRIPTION
**Pull request by tijmenb**
Meant as an alternative to https://github.com/alphagov/publishing-api/pull/286.

@elliotcm 👍 on [the docs](http://www.rubydoc.info/github/alphagov/gds-api-adapters/master/GdsApi/PublishingApiV2#unpublish-instance_method), super useful.

### CODE REVIEW

**Comment by tijmenb** [comment]
Perhaps a bug in publishing-api, @elliotcm will investigate.

**Comment by elliotcm** [comment]
@tijmenb https://github.com/alphagov/publishing-api/pull/297

**Comment by tijmenb** [comment]
Will reopen this branch once https://github.com/alphagov/publishing-api/pull/297 is deployed.

**Comment by tijmenb** [comment]
https://github.com/alphagov/publishing-api/pull/297 has been deployed, we can try this again.

**Pull request merged**
