### PR TITLE
Remove all migrations which rely on data

### PR DESCRIPTION
**Pull request by tommyp**
Building this App from scratch requires running the migrations. A number
of these migrations ran code which either relied on columns added later
in the migrations, code that has been removed or data that needed to be
present but wasn't added because of an earlier failing migration. This
commit removes any of these migrations and reruns `db:create db:migrate
db:seed` to make sure that the new list of migrations can be ran.

### CODE REVIEW

**Comment by ajlanghorn** [comment]
@surminus This should hopefully fix the deployment error we saw earlier on.

**Comment by elliotcm** [comment]
There's some conceptual issues with this in that while it's probably fine to delete old migrations the idiomatic Rails way of bootstrapping an app is via `rake db:schema:load` not by running all the migrations start to finish.  This is because of the data issues you're encountering and also because classes and methods change over time and may not be available in the newest code.

If you're deploying the app on new infrastructure we should have a deploy task geared towards that.  This is discussed in more detail here: http://stackoverflow.com/questions/1329778/dbschemaload-vs-dbmigrate-with-capistrano

If you want to just get on with things you could use the "delete things" method, or load the DB from production, or run `rake db:schema:load` manually.

**Comment by ajlanghorn** [comment]
@elliotcm In discussing with @alext, we realised that we didn't actually have a successful dump of the database this relies on yet. I'm going to get that working first, to hopefully resolve the deployment issue. @alext mentioned that `db:schema:load` was a better way of doing this, but as we have no database yet, that will probably error for similar reasons :sunglasses:

**Comment by elliotcm** [comment]
@ajlanghorn Cool.  That said, `db:schema:load` will work so long as even an empty database exists with the right permissions.

**Comment by ajlanghorn** [comment]
@elliotcm Good to know; thanks. At the moment, the PostgreSQL dump has failed for the last two attempts, but intermittently appears to work. This calls for a :headphones:-tastic afternoon!

**Comment by tommyp** [comment]
@ajlanghorn Is this PR still needed or can we close it?

**Comment by ajlanghorn** [comment]
Nah, can be closed. Thanks @elliotcm and @tommyp.

**Pull request closed without merging**
