### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by tijmenb**
Adds screenshot and updates the explanations.

Trello: https://trello.com/c/d3RlTJwt

To be reviewed by two people from @alphagov/team-finding-things.

### CODE REVIEW

**Comment by MatMoore** [comment]
:question: Can we provide an example of what a policy/subpolicy actually is and how end users see them? Is subpolicy just a policy with a parent (similar to a "subtopic") or is it a distinct thing?

**Comment by tijmenb** [comment]
@MatMoore I think that is mentioned in the nomenclature? https://github.com/alphagov/policy-publisher/blob/readme-update/README.md#nomenclature

**Comment by MatMoore** [comment]
Whoops, missed that part. In that case :+1: from me.

**Comment by Davidslv** [comment]
👍

**Pull request merged**
